/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocksx127x_util.h"
#include "mock_helper.h"

static const char* CMockString_data = "data";
static const char* CMockString_data_length = "data_length";
static const char* CMockString_device = "device";
static const char* CMockString_frame = "frame";
static const char* CMockString_lora_util_frame_destroy = "lora_util_frame_destroy";
static const char* CMockString_lora_util_init = "lora_util_init";
static const char* CMockString_lora_util_read_frame = "lora_util_read_frame";
static const char* CMockString_lora_util_start_rx = "lora_util_start_rx";
static const char* CMockString_lora_util_start_tx = "lora_util_start_tx";
static const char* CMockString_req = "req";
static const char* CMockString_result = "result";

typedef struct _CMOCK_lora_util_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  sx127x** Expected_device;
  int Expected_device_Depth;
  char ReturnThruPtr_device_Used;
  sx127x** ReturnThruPtr_device_Val;
  int ReturnThruPtr_device_Size;
  char IgnoreArg_device;

} CMOCK_lora_util_init_CALL_INSTANCE;

typedef struct _CMOCK_lora_util_read_frame_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  sx127x* Expected_device;
  uint8_t* Expected_data;
  uint16_t Expected_data_length;
  lora_frame_t** Expected_result;
  int Expected_device_Depth;
  int Expected_data_Depth;
  int Expected_result_Depth;
  char ReturnThruPtr_device_Used;
  sx127x* ReturnThruPtr_device_Val;
  int ReturnThruPtr_device_Size;
  char ReturnThruPtr_data_Used;
  uint8_t* ReturnThruPtr_data_Val;
  int ReturnThruPtr_data_Size;
  char ReturnThruPtr_result_Used;
  lora_frame_t** ReturnThruPtr_result_Val;
  int ReturnThruPtr_result_Size;
  char IgnoreArg_device;
  char IgnoreArg_data;
  char IgnoreArg_data_length;
  char IgnoreArg_result;

} CMOCK_lora_util_read_frame_CALL_INSTANCE;

typedef struct _CMOCK_lora_util_start_rx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  rx_request_t* Expected_req;
  sx127x* Expected_device;
  int Expected_req_Depth;
  int Expected_device_Depth;
  char ReturnThruPtr_req_Used;
  rx_request_t* ReturnThruPtr_req_Val;
  int ReturnThruPtr_req_Size;
  char ReturnThruPtr_device_Used;
  sx127x* ReturnThruPtr_device_Val;
  int ReturnThruPtr_device_Size;
  char IgnoreArg_req;
  char IgnoreArg_device;

} CMOCK_lora_util_start_rx_CALL_INSTANCE;

typedef struct _CMOCK_lora_util_start_tx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  uint8_t* Expected_data;
  size_t Expected_data_length;
  rx_request_t* Expected_req;
  sx127x* Expected_device;
  int Expected_data_Depth;
  int Expected_req_Depth;
  int Expected_device_Depth;
  char ReturnThruPtr_data_Used;
  uint8_t* ReturnThruPtr_data_Val;
  int ReturnThruPtr_data_Size;
  char ReturnThruPtr_req_Used;
  rx_request_t* ReturnThruPtr_req_Val;
  int ReturnThruPtr_req_Size;
  char ReturnThruPtr_device_Used;
  sx127x* ReturnThruPtr_device_Val;
  int ReturnThruPtr_device_Size;
  char IgnoreArg_data;
  char IgnoreArg_data_length;
  char IgnoreArg_req;
  char IgnoreArg_device;

} CMOCK_lora_util_start_tx_CALL_INSTANCE;

typedef struct _CMOCK_lora_util_frame_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  lora_frame_t* Expected_frame;
  int Expected_frame_Depth;
  char ReturnThruPtr_frame_Used;
  lora_frame_t* ReturnThruPtr_frame_Val;
  int ReturnThruPtr_frame_Size;
  char IgnoreArg_frame;

} CMOCK_lora_util_frame_destroy_CALL_INSTANCE;

static struct Mocksx127x_utilInstance
{
  char lora_util_init_IgnoreBool;
  esp_err_t lora_util_init_FinalReturn;
  char lora_util_init_CallbackBool;
  CMOCK_lora_util_init_CALLBACK lora_util_init_CallbackFunctionPointer;
  int lora_util_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_util_init_CallInstance;
  char lora_util_read_frame_IgnoreBool;
  esp_err_t lora_util_read_frame_FinalReturn;
  char lora_util_read_frame_CallbackBool;
  CMOCK_lora_util_read_frame_CALLBACK lora_util_read_frame_CallbackFunctionPointer;
  int lora_util_read_frame_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_util_read_frame_CallInstance;
  char lora_util_start_rx_IgnoreBool;
  esp_err_t lora_util_start_rx_FinalReturn;
  char lora_util_start_rx_CallbackBool;
  CMOCK_lora_util_start_rx_CALLBACK lora_util_start_rx_CallbackFunctionPointer;
  int lora_util_start_rx_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_util_start_rx_CallInstance;
  char lora_util_start_tx_IgnoreBool;
  esp_err_t lora_util_start_tx_FinalReturn;
  char lora_util_start_tx_CallbackBool;
  CMOCK_lora_util_start_tx_CALLBACK lora_util_start_tx_CallbackFunctionPointer;
  int lora_util_start_tx_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_util_start_tx_CallInstance;
  char lora_util_frame_destroy_IgnoreBool;
  char lora_util_frame_destroy_CallbackBool;
  CMOCK_lora_util_frame_destroy_CALLBACK lora_util_frame_destroy_CallbackFunctionPointer;
  int lora_util_frame_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_util_frame_destroy_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksx127x_util_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.lora_util_init_CallInstance;
  if (Mock.lora_util_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_util_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_util_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_util_read_frame_CallInstance;
  if (Mock.lora_util_read_frame_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_util_read_frame);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_util_read_frame_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_util_start_rx_CallInstance;
  if (Mock.lora_util_start_rx_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_util_start_rx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_util_start_rx_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_util_start_tx_CallInstance;
  if (Mock.lora_util_start_tx_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_util_start_tx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_util_start_tx_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_util_frame_destroy_CallInstance;
  if (Mock.lora_util_frame_destroy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_util_frame_destroy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_util_frame_destroy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocksx127x_util_Init(void)
{
  Mocksx127x_util_Destroy();
}

void Mocksx127x_util_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t lora_util_init(sx127x** device)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_util_init);
  cmock_call_instance = (CMOCK_lora_util_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_util_init_CallInstance);
  Mock.lora_util_init_CallInstance = CMock_Guts_MemNext(Mock.lora_util_init_CallInstance);
  if (Mock.lora_util_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_util_init_FinalReturn;
    memcpy((void*)(&Mock.lora_util_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_util_init_CallbackBool &&
      Mock.lora_util_init_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_util_init_CallbackFunctionPointer(device, Mock.lora_util_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_device)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_init,CMockString_device);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_device, device, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.lora_util_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_util_init_CallbackFunctionPointer(device, Mock.lora_util_init_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_device_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(device, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)device, (void*)cmock_call_instance->ReturnThruPtr_device_Val,
      cmock_call_instance->ReturnThruPtr_device_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_util_init(CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance, sx127x** device, int device_Depth)
{
  cmock_call_instance->Expected_device = device;
  cmock_call_instance->Expected_device_Depth = device_Depth;
  cmock_call_instance->IgnoreArg_device = 0;
  cmock_call_instance->ReturnThruPtr_device_Used = 0;
}

void lora_util_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_init_CALL_INSTANCE));
  CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_init_CallInstance = CMock_Guts_MemChain(Mock.lora_util_init_CallInstance, cmock_guts_index);
  Mock.lora_util_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_util_init_IgnoreBool = (char)1;
}

void lora_util_init_CMockStopIgnore(void)
{
  if(Mock.lora_util_init_IgnoreBool)
    Mock.lora_util_init_CallInstance = CMock_Guts_MemNext(Mock.lora_util_init_CallInstance);
  Mock.lora_util_init_IgnoreBool = (char)0;
}

void lora_util_init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_init_CALL_INSTANCE));
  CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_init_CallInstance = CMock_Guts_MemChain(Mock.lora_util_init_CallInstance, cmock_guts_index);
  Mock.lora_util_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_util_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sx127x** device, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_init_CALL_INSTANCE));
  CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_init_CallInstance = CMock_Guts_MemChain(Mock.lora_util_init_CallInstance, cmock_guts_index);
  Mock.lora_util_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_init(cmock_call_instance, device, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_util_init_AddCallback(CMOCK_lora_util_init_CALLBACK Callback)
{
  Mock.lora_util_init_IgnoreBool = (char)0;
  Mock.lora_util_init_CallbackBool = (char)1;
  Mock.lora_util_init_CallbackFunctionPointer = Callback;
}

void lora_util_init_Stub(CMOCK_lora_util_init_CALLBACK Callback)
{
  Mock.lora_util_init_IgnoreBool = (char)0;
  Mock.lora_util_init_CallbackBool = (char)0;
  Mock.lora_util_init_CallbackFunctionPointer = Callback;
}

void lora_util_init_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, sx127x** device, int device_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_init_CALL_INSTANCE));
  CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_init_CallInstance = CMock_Guts_MemChain(Mock.lora_util_init_CallInstance, cmock_guts_index);
  Mock.lora_util_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_init(cmock_call_instance, device, device_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_util_init_CMockReturnMemThruPtr_device(UNITY_LINE_TYPE cmock_line, sx127x** device, int cmock_size)
{
  CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_device_Used = 1;
  cmock_call_instance->ReturnThruPtr_device_Val = device;
  cmock_call_instance->ReturnThruPtr_device_Size = cmock_size;
}

void lora_util_init_CMockIgnoreArg_device(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_device = 1;
}

esp_err_t lora_util_read_frame(sx127x* device, uint8_t* data, uint16_t data_length, lora_frame_t** result)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_util_read_frame);
  cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_util_read_frame_CallInstance);
  Mock.lora_util_read_frame_CallInstance = CMock_Guts_MemNext(Mock.lora_util_read_frame_CallInstance);
  if (Mock.lora_util_read_frame_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_util_read_frame_FinalReturn;
    memcpy((void*)(&Mock.lora_util_read_frame_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_util_read_frame_CallbackBool &&
      Mock.lora_util_read_frame_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_util_read_frame_CallbackFunctionPointer(device, data, data_length, result, Mock.lora_util_read_frame_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_device)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_read_frame,CMockString_device);
    if (cmock_call_instance->Expected_device == NULL)
      { UNITY_TEST_ASSERT_NULL(device, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_device), (void*)(device), sizeof(sx127x), cmock_call_instance->Expected_device_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_read_frame,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_data_length)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_read_frame,CMockString_data_length);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data_length, data_length, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_result)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_read_frame,CMockString_result);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_result, result, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.lora_util_read_frame_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_util_read_frame_CallbackFunctionPointer(device, data, data_length, result, Mock.lora_util_read_frame_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_device_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(device, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)device, (void*)cmock_call_instance->ReturnThruPtr_device_Val,
      cmock_call_instance->ReturnThruPtr_device_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)data, (void*)cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_result_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(result, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)result, (void*)cmock_call_instance->ReturnThruPtr_result_Val,
      cmock_call_instance->ReturnThruPtr_result_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_util_read_frame(CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance, sx127x* device, int device_Depth, uint8_t* data, int data_Depth, uint16_t data_length, lora_frame_t** result, int result_Depth)
{
  cmock_call_instance->Expected_device = device;
  cmock_call_instance->Expected_device_Depth = device_Depth;
  cmock_call_instance->IgnoreArg_device = 0;
  cmock_call_instance->ReturnThruPtr_device_Used = 0;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
  cmock_call_instance->Expected_data_length = data_length;
  cmock_call_instance->IgnoreArg_data_length = 0;
  cmock_call_instance->Expected_result = result;
  cmock_call_instance->Expected_result_Depth = result_Depth;
  cmock_call_instance->IgnoreArg_result = 0;
  cmock_call_instance->ReturnThruPtr_result_Used = 0;
}

void lora_util_read_frame_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_read_frame_CALL_INSTANCE));
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_read_frame_CallInstance = CMock_Guts_MemChain(Mock.lora_util_read_frame_CallInstance, cmock_guts_index);
  Mock.lora_util_read_frame_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_util_read_frame_IgnoreBool = (char)1;
}

void lora_util_read_frame_CMockStopIgnore(void)
{
  if(Mock.lora_util_read_frame_IgnoreBool)
    Mock.lora_util_read_frame_CallInstance = CMock_Guts_MemNext(Mock.lora_util_read_frame_CallInstance);
  Mock.lora_util_read_frame_IgnoreBool = (char)0;
}

void lora_util_read_frame_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_read_frame_CALL_INSTANCE));
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_read_frame_CallInstance = CMock_Guts_MemChain(Mock.lora_util_read_frame_CallInstance, cmock_guts_index);
  Mock.lora_util_read_frame_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_util_read_frame_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sx127x* device, uint8_t* data, uint16_t data_length, lora_frame_t** result, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_read_frame_CALL_INSTANCE));
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_read_frame_CallInstance = CMock_Guts_MemChain(Mock.lora_util_read_frame_CallInstance, cmock_guts_index);
  Mock.lora_util_read_frame_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_read_frame(cmock_call_instance, device, 1, data, 1, data_length, result, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_util_read_frame_AddCallback(CMOCK_lora_util_read_frame_CALLBACK Callback)
{
  Mock.lora_util_read_frame_IgnoreBool = (char)0;
  Mock.lora_util_read_frame_CallbackBool = (char)1;
  Mock.lora_util_read_frame_CallbackFunctionPointer = Callback;
}

void lora_util_read_frame_Stub(CMOCK_lora_util_read_frame_CALLBACK Callback)
{
  Mock.lora_util_read_frame_IgnoreBool = (char)0;
  Mock.lora_util_read_frame_CallbackBool = (char)0;
  Mock.lora_util_read_frame_CallbackFunctionPointer = Callback;
}

void lora_util_read_frame_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, sx127x* device, int device_Depth, uint8_t* data, int data_Depth, uint16_t data_length, lora_frame_t** result, int result_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_read_frame_CALL_INSTANCE));
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_read_frame_CallInstance = CMock_Guts_MemChain(Mock.lora_util_read_frame_CallInstance, cmock_guts_index);
  Mock.lora_util_read_frame_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_read_frame(cmock_call_instance, device, device_Depth, data, data_Depth, data_length, result, result_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_util_read_frame_CMockReturnMemThruPtr_device(UNITY_LINE_TYPE cmock_line, sx127x* device, int cmock_size)
{
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_read_frame_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_device_Used = 1;
  cmock_call_instance->ReturnThruPtr_device_Val = device;
  cmock_call_instance->ReturnThruPtr_device_Size = cmock_size;
}

void lora_util_read_frame_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, uint8_t* data, int cmock_size)
{
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_read_frame_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void lora_util_read_frame_CMockReturnMemThruPtr_result(UNITY_LINE_TYPE cmock_line, lora_frame_t** result, int cmock_size)
{
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_read_frame_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_result_Used = 1;
  cmock_call_instance->ReturnThruPtr_result_Val = result;
  cmock_call_instance->ReturnThruPtr_result_Size = cmock_size;
}

void lora_util_read_frame_CMockIgnoreArg_device(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_read_frame_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_device = 1;
}

void lora_util_read_frame_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_read_frame_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void lora_util_read_frame_CMockIgnoreArg_data_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_read_frame_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data_length = 1;
}

void lora_util_read_frame_CMockIgnoreArg_result(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_read_frame_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_read_frame_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_read_frame_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_result = 1;
}

esp_err_t lora_util_start_rx(rx_request_t* req, sx127x* device)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_util_start_rx);
  cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_util_start_rx_CallInstance);
  Mock.lora_util_start_rx_CallInstance = CMock_Guts_MemNext(Mock.lora_util_start_rx_CallInstance);
  if (Mock.lora_util_start_rx_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_util_start_rx_FinalReturn;
    memcpy((void*)(&Mock.lora_util_start_rx_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_util_start_rx_CallbackBool &&
      Mock.lora_util_start_rx_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_util_start_rx_CallbackFunctionPointer(req, device, Mock.lora_util_start_rx_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_req)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_start_rx,CMockString_req);
    if (cmock_call_instance->Expected_req == NULL)
      { UNITY_TEST_ASSERT_NULL(req, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_req), (void*)(req), sizeof(rx_request_t), cmock_call_instance->Expected_req_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_device)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_start_rx,CMockString_device);
    if (cmock_call_instance->Expected_device == NULL)
      { UNITY_TEST_ASSERT_NULL(device, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_device), (void*)(device), sizeof(sx127x), cmock_call_instance->Expected_device_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.lora_util_start_rx_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_util_start_rx_CallbackFunctionPointer(req, device, Mock.lora_util_start_rx_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_req_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(req, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)req, (void*)cmock_call_instance->ReturnThruPtr_req_Val,
      cmock_call_instance->ReturnThruPtr_req_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_device_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(device, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)device, (void*)cmock_call_instance->ReturnThruPtr_device_Val,
      cmock_call_instance->ReturnThruPtr_device_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_util_start_rx(CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance, rx_request_t* req, int req_Depth, sx127x* device, int device_Depth)
{
  cmock_call_instance->Expected_req = req;
  cmock_call_instance->Expected_req_Depth = req_Depth;
  cmock_call_instance->IgnoreArg_req = 0;
  cmock_call_instance->ReturnThruPtr_req_Used = 0;
  cmock_call_instance->Expected_device = device;
  cmock_call_instance->Expected_device_Depth = device_Depth;
  cmock_call_instance->IgnoreArg_device = 0;
  cmock_call_instance->ReturnThruPtr_device_Used = 0;
}

void lora_util_start_rx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_rx_CALL_INSTANCE));
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_rx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_rx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_rx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_util_start_rx_IgnoreBool = (char)1;
}

void lora_util_start_rx_CMockStopIgnore(void)
{
  if(Mock.lora_util_start_rx_IgnoreBool)
    Mock.lora_util_start_rx_CallInstance = CMock_Guts_MemNext(Mock.lora_util_start_rx_CallInstance);
  Mock.lora_util_start_rx_IgnoreBool = (char)0;
}

void lora_util_start_rx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_rx_CALL_INSTANCE));
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_rx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_rx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_rx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_util_start_rx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, rx_request_t* req, sx127x* device, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_rx_CALL_INSTANCE));
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_rx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_rx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_rx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_start_rx(cmock_call_instance, req, 1, device, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_util_start_rx_AddCallback(CMOCK_lora_util_start_rx_CALLBACK Callback)
{
  Mock.lora_util_start_rx_IgnoreBool = (char)0;
  Mock.lora_util_start_rx_CallbackBool = (char)1;
  Mock.lora_util_start_rx_CallbackFunctionPointer = Callback;
}

void lora_util_start_rx_Stub(CMOCK_lora_util_start_rx_CALLBACK Callback)
{
  Mock.lora_util_start_rx_IgnoreBool = (char)0;
  Mock.lora_util_start_rx_CallbackBool = (char)0;
  Mock.lora_util_start_rx_CallbackFunctionPointer = Callback;
}

void lora_util_start_rx_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, rx_request_t* req, int req_Depth, sx127x* device, int device_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_rx_CALL_INSTANCE));
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_rx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_rx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_rx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_start_rx(cmock_call_instance, req, req_Depth, device, device_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_util_start_rx_CMockReturnMemThruPtr_req(UNITY_LINE_TYPE cmock_line, rx_request_t* req, int cmock_size)
{
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_rx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_req_Used = 1;
  cmock_call_instance->ReturnThruPtr_req_Val = req;
  cmock_call_instance->ReturnThruPtr_req_Size = cmock_size;
}

void lora_util_start_rx_CMockReturnMemThruPtr_device(UNITY_LINE_TYPE cmock_line, sx127x* device, int cmock_size)
{
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_rx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_device_Used = 1;
  cmock_call_instance->ReturnThruPtr_device_Val = device;
  cmock_call_instance->ReturnThruPtr_device_Size = cmock_size;
}

void lora_util_start_rx_CMockIgnoreArg_req(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_rx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_req = 1;
}

void lora_util_start_rx_CMockIgnoreArg_device(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_start_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_rx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_device = 1;
}

esp_err_t lora_util_start_tx(uint8_t* data, size_t data_length, rx_request_t* req, sx127x* device)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_util_start_tx);
  cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_util_start_tx_CallInstance);
  Mock.lora_util_start_tx_CallInstance = CMock_Guts_MemNext(Mock.lora_util_start_tx_CallInstance);
  if (Mock.lora_util_start_tx_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_util_start_tx_FinalReturn;
    memcpy((void*)(&Mock.lora_util_start_tx_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_util_start_tx_CallbackBool &&
      Mock.lora_util_start_tx_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_util_start_tx_CallbackFunctionPointer(data, data_length, req, device, Mock.lora_util_start_tx_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_start_tx,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_data_length)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_start_tx,CMockString_data_length);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_data_length), (void*)(&data_length), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_req)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_start_tx,CMockString_req);
    if (cmock_call_instance->Expected_req == NULL)
      { UNITY_TEST_ASSERT_NULL(req, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_req), (void*)(req), sizeof(rx_request_t), cmock_call_instance->Expected_req_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_device)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_start_tx,CMockString_device);
    if (cmock_call_instance->Expected_device == NULL)
      { UNITY_TEST_ASSERT_NULL(device, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_device), (void*)(device), sizeof(sx127x), cmock_call_instance->Expected_device_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.lora_util_start_tx_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_util_start_tx_CallbackFunctionPointer(data, data_length, req, device, Mock.lora_util_start_tx_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)data, (void*)cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_req_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(req, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)req, (void*)cmock_call_instance->ReturnThruPtr_req_Val,
      cmock_call_instance->ReturnThruPtr_req_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_device_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(device, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)device, (void*)cmock_call_instance->ReturnThruPtr_device_Val,
      cmock_call_instance->ReturnThruPtr_device_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_util_start_tx(CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance, uint8_t* data, int data_Depth, size_t data_length, rx_request_t* req, int req_Depth, sx127x* device, int device_Depth)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_data_length), (void*)(&data_length),
         sizeof(size_t[sizeof(data_length) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_data_length = 0;
  cmock_call_instance->Expected_req = req;
  cmock_call_instance->Expected_req_Depth = req_Depth;
  cmock_call_instance->IgnoreArg_req = 0;
  cmock_call_instance->ReturnThruPtr_req_Used = 0;
  cmock_call_instance->Expected_device = device;
  cmock_call_instance->Expected_device_Depth = device_Depth;
  cmock_call_instance->IgnoreArg_device = 0;
  cmock_call_instance->ReturnThruPtr_device_Used = 0;
}

void lora_util_start_tx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_tx_CALL_INSTANCE));
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_tx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_tx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_tx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_util_start_tx_IgnoreBool = (char)1;
}

void lora_util_start_tx_CMockStopIgnore(void)
{
  if(Mock.lora_util_start_tx_IgnoreBool)
    Mock.lora_util_start_tx_CallInstance = CMock_Guts_MemNext(Mock.lora_util_start_tx_CallInstance);
  Mock.lora_util_start_tx_IgnoreBool = (char)0;
}

void lora_util_start_tx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_tx_CALL_INSTANCE));
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_tx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_tx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_tx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_util_start_tx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* data, size_t data_length, rx_request_t* req, sx127x* device, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_tx_CALL_INSTANCE));
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_tx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_tx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_tx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_start_tx(cmock_call_instance, data, data_length, data_length, req, 1, device, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_util_start_tx_AddCallback(CMOCK_lora_util_start_tx_CALLBACK Callback)
{
  Mock.lora_util_start_tx_IgnoreBool = (char)0;
  Mock.lora_util_start_tx_CallbackBool = (char)1;
  Mock.lora_util_start_tx_CallbackFunctionPointer = Callback;
}

void lora_util_start_tx_Stub(CMOCK_lora_util_start_tx_CALLBACK Callback)
{
  Mock.lora_util_start_tx_IgnoreBool = (char)0;
  Mock.lora_util_start_tx_CallbackBool = (char)0;
  Mock.lora_util_start_tx_CallbackFunctionPointer = Callback;
}

void lora_util_start_tx_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* data, int data_Depth, size_t data_length, rx_request_t* req, int req_Depth, sx127x* device, int device_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_start_tx_CALL_INSTANCE));
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_start_tx_CallInstance = CMock_Guts_MemChain(Mock.lora_util_start_tx_CallInstance, cmock_guts_index);
  Mock.lora_util_start_tx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_start_tx(cmock_call_instance, data, data_Depth, data_length, req, req_Depth, device, device_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_util_start_tx_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, uint8_t* data, int cmock_size)
{
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_tx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void lora_util_start_tx_CMockReturnMemThruPtr_req(UNITY_LINE_TYPE cmock_line, rx_request_t* req, int cmock_size)
{
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_tx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_req_Used = 1;
  cmock_call_instance->ReturnThruPtr_req_Val = req;
  cmock_call_instance->ReturnThruPtr_req_Size = cmock_size;
}

void lora_util_start_tx_CMockReturnMemThruPtr_device(UNITY_LINE_TYPE cmock_line, sx127x* device, int cmock_size)
{
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_tx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_device_Used = 1;
  cmock_call_instance->ReturnThruPtr_device_Val = device;
  cmock_call_instance->ReturnThruPtr_device_Size = cmock_size;
}

void lora_util_start_tx_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_tx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void lora_util_start_tx_CMockIgnoreArg_data_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_tx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data_length = 1;
}

void lora_util_start_tx_CMockIgnoreArg_req(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_tx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_req = 1;
}

void lora_util_start_tx_CMockIgnoreArg_device(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_start_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_start_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_start_tx_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_device = 1;
}

void lora_util_frame_destroy(lora_frame_t* frame)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_util_frame_destroy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_util_frame_destroy);
  cmock_call_instance = (CMOCK_lora_util_frame_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_util_frame_destroy_CallInstance);
  Mock.lora_util_frame_destroy_CallInstance = CMock_Guts_MemNext(Mock.lora_util_frame_destroy_CallInstance);
  if (Mock.lora_util_frame_destroy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.lora_util_frame_destroy_CallbackBool &&
      Mock.lora_util_frame_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.lora_util_frame_destroy_CallbackFunctionPointer(frame, Mock.lora_util_frame_destroy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_frame)
  {
    UNITY_SET_DETAILS(CMockString_lora_util_frame_destroy,CMockString_frame);
    if (cmock_call_instance->Expected_frame == NULL)
      { UNITY_TEST_ASSERT_NULL(frame, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_frame), (void*)(frame), sizeof(lora_frame_t), cmock_call_instance->Expected_frame_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.lora_util_frame_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.lora_util_frame_destroy_CallbackFunctionPointer(frame, Mock.lora_util_frame_destroy_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_frame_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(frame, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)frame, (void*)cmock_call_instance->ReturnThruPtr_frame_Val,
      cmock_call_instance->ReturnThruPtr_frame_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_lora_util_frame_destroy(CMOCK_lora_util_frame_destroy_CALL_INSTANCE* cmock_call_instance, lora_frame_t* frame, int frame_Depth)
{
  cmock_call_instance->Expected_frame = frame;
  cmock_call_instance->Expected_frame_Depth = frame_Depth;
  cmock_call_instance->IgnoreArg_frame = 0;
  cmock_call_instance->ReturnThruPtr_frame_Used = 0;
}

void lora_util_frame_destroy_CMockIgnore(void)
{
  Mock.lora_util_frame_destroy_IgnoreBool = (char)1;
}

void lora_util_frame_destroy_CMockStopIgnore(void)
{
  Mock.lora_util_frame_destroy_IgnoreBool = (char)0;
}

void lora_util_frame_destroy_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_frame_destroy_CALL_INSTANCE));
  CMOCK_lora_util_frame_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_frame_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_frame_destroy_CallInstance = CMock_Guts_MemChain(Mock.lora_util_frame_destroy_CallInstance, cmock_guts_index);
  Mock.lora_util_frame_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_util_frame_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, lora_frame_t* frame)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_frame_destroy_CALL_INSTANCE));
  CMOCK_lora_util_frame_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_frame_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_frame_destroy_CallInstance = CMock_Guts_MemChain(Mock.lora_util_frame_destroy_CallInstance, cmock_guts_index);
  Mock.lora_util_frame_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_frame_destroy(cmock_call_instance, frame, 1);
}

void lora_util_frame_destroy_AddCallback(CMOCK_lora_util_frame_destroy_CALLBACK Callback)
{
  Mock.lora_util_frame_destroy_IgnoreBool = (char)0;
  Mock.lora_util_frame_destroy_CallbackBool = (char)1;
  Mock.lora_util_frame_destroy_CallbackFunctionPointer = Callback;
}

void lora_util_frame_destroy_Stub(CMOCK_lora_util_frame_destroy_CALLBACK Callback)
{
  Mock.lora_util_frame_destroy_IgnoreBool = (char)0;
  Mock.lora_util_frame_destroy_CallbackBool = (char)0;
  Mock.lora_util_frame_destroy_CallbackFunctionPointer = Callback;
}

void lora_util_frame_destroy_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, lora_frame_t* frame, int frame_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_util_frame_destroy_CALL_INSTANCE));
  CMOCK_lora_util_frame_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_frame_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_util_frame_destroy_CallInstance = CMock_Guts_MemChain(Mock.lora_util_frame_destroy_CallInstance, cmock_guts_index);
  Mock.lora_util_frame_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_util_frame_destroy(cmock_call_instance, frame, frame_Depth);
}

void lora_util_frame_destroy_CMockReturnMemThruPtr_frame(UNITY_LINE_TYPE cmock_line, lora_frame_t* frame, int cmock_size)
{
  CMOCK_lora_util_frame_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_frame_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_frame_destroy_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_frame_Used = 1;
  cmock_call_instance->ReturnThruPtr_frame_Val = frame;
  cmock_call_instance->ReturnThruPtr_frame_Size = cmock_size;
}

void lora_util_frame_destroy_CMockIgnoreArg_frame(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_util_frame_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_util_frame_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_util_frame_destroy_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_frame = 1;
}

