/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDISPLAY_H
#define _MOCKDISPLAY_H

#include "unity.h"
#include "display.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockdisplay_Init(void);
void Mockdisplay_Destroy(void);
void Mockdisplay_Verify(void);




#define lora_at_display_create_IgnoreAndReturn(cmock_retval) lora_at_display_create_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void lora_at_display_create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_create_StopIgnore() lora_at_display_create_CMockStopIgnore()
void lora_at_display_create_CMockStopIgnore(void);
#define lora_at_display_create_ExpectAnyArgsAndReturn(cmock_retval) lora_at_display_create_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void lora_at_display_create_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_create_ExpectAndReturn(display, cmock_retval) lora_at_display_create_CMockExpectAndReturn(__LINE__, display, cmock_retval)
void lora_at_display_create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display** display, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_lora_at_display_create_CALLBACK)(lora_at_display** display, int cmock_num_calls);
void lora_at_display_create_AddCallback(CMOCK_lora_at_display_create_CALLBACK Callback);
void lora_at_display_create_Stub(CMOCK_lora_at_display_create_CALLBACK Callback);
#define lora_at_display_create_StubWithCallback lora_at_display_create_Stub
#define lora_at_display_create_ExpectWithArrayAndReturn(display, display_Depth, cmock_retval) lora_at_display_create_CMockExpectWithArrayAndReturn(__LINE__, display, display_Depth, cmock_retval)
void lora_at_display_create_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display** display, int display_Depth, esp_err_t cmock_to_return);
#define lora_at_display_create_ReturnThruPtr_display(display) lora_at_display_create_CMockReturnMemThruPtr_display(__LINE__, display, sizeof(lora_at_display*))
#define lora_at_display_create_ReturnArrayThruPtr_display(display, cmock_len) lora_at_display_create_CMockReturnMemThruPtr_display(__LINE__, display, (int)(cmock_len * (int)sizeof(*display)))
#define lora_at_display_create_ReturnMemThruPtr_display(display, cmock_size) lora_at_display_create_CMockReturnMemThruPtr_display(__LINE__, display, cmock_size)
void lora_at_display_create_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display** display, int cmock_size);
#define lora_at_display_create_IgnoreArg_display() lora_at_display_create_CMockIgnoreArg_display(__LINE__)
void lora_at_display_create_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line);
#define lora_at_display_start_IgnoreAndReturn(cmock_retval) lora_at_display_start_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void lora_at_display_start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_start_StopIgnore() lora_at_display_start_CMockStopIgnore()
void lora_at_display_start_CMockStopIgnore(void);
#define lora_at_display_start_ExpectAnyArgsAndReturn(cmock_retval) lora_at_display_start_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void lora_at_display_start_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_start_ExpectAndReturn(display, cmock_retval) lora_at_display_start_CMockExpectAndReturn(__LINE__, display, cmock_retval)
void lora_at_display_start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_lora_at_display_start_CALLBACK)(lora_at_display* display, int cmock_num_calls);
void lora_at_display_start_AddCallback(CMOCK_lora_at_display_start_CALLBACK Callback);
void lora_at_display_start_Stub(CMOCK_lora_at_display_start_CALLBACK Callback);
#define lora_at_display_start_StubWithCallback lora_at_display_start_Stub
#define lora_at_display_start_ExpectWithArrayAndReturn(display, display_Depth, cmock_retval) lora_at_display_start_CMockExpectWithArrayAndReturn(__LINE__, display, display_Depth, cmock_retval)
void lora_at_display_start_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int display_Depth, esp_err_t cmock_to_return);
#define lora_at_display_start_ReturnThruPtr_display(display) lora_at_display_start_CMockReturnMemThruPtr_display(__LINE__, display, sizeof(lora_at_display))
#define lora_at_display_start_ReturnArrayThruPtr_display(display, cmock_len) lora_at_display_start_CMockReturnMemThruPtr_display(__LINE__, display, (int)(cmock_len * (int)sizeof(*display)))
#define lora_at_display_start_ReturnMemThruPtr_display(display, cmock_size) lora_at_display_start_CMockReturnMemThruPtr_display(__LINE__, display, cmock_size)
void lora_at_display_start_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size);
#define lora_at_display_start_IgnoreArg_display() lora_at_display_start_CMockIgnoreArg_display(__LINE__)
void lora_at_display_start_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line);
#define lora_at_display_stop_IgnoreAndReturn(cmock_retval) lora_at_display_stop_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void lora_at_display_stop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_stop_StopIgnore() lora_at_display_stop_CMockStopIgnore()
void lora_at_display_stop_CMockStopIgnore(void);
#define lora_at_display_stop_ExpectAnyArgsAndReturn(cmock_retval) lora_at_display_stop_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void lora_at_display_stop_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_stop_ExpectAndReturn(display, cmock_retval) lora_at_display_stop_CMockExpectAndReturn(__LINE__, display, cmock_retval)
void lora_at_display_stop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_lora_at_display_stop_CALLBACK)(lora_at_display* display, int cmock_num_calls);
void lora_at_display_stop_AddCallback(CMOCK_lora_at_display_stop_CALLBACK Callback);
void lora_at_display_stop_Stub(CMOCK_lora_at_display_stop_CALLBACK Callback);
#define lora_at_display_stop_StubWithCallback lora_at_display_stop_Stub
#define lora_at_display_stop_ExpectWithArrayAndReturn(display, display_Depth, cmock_retval) lora_at_display_stop_CMockExpectWithArrayAndReturn(__LINE__, display, display_Depth, cmock_retval)
void lora_at_display_stop_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int display_Depth, esp_err_t cmock_to_return);
#define lora_at_display_stop_ReturnThruPtr_display(display) lora_at_display_stop_CMockReturnMemThruPtr_display(__LINE__, display, sizeof(lora_at_display))
#define lora_at_display_stop_ReturnArrayThruPtr_display(display, cmock_len) lora_at_display_stop_CMockReturnMemThruPtr_display(__LINE__, display, (int)(cmock_len * (int)sizeof(*display)))
#define lora_at_display_stop_ReturnMemThruPtr_display(display, cmock_size) lora_at_display_stop_CMockReturnMemThruPtr_display(__LINE__, display, cmock_size)
void lora_at_display_stop_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size);
#define lora_at_display_stop_IgnoreArg_display() lora_at_display_stop_CMockIgnoreArg_display(__LINE__)
void lora_at_display_stop_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line);
#define lora_at_display_set_status_IgnoreAndReturn(cmock_retval) lora_at_display_set_status_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void lora_at_display_set_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_set_status_StopIgnore() lora_at_display_set_status_CMockStopIgnore()
void lora_at_display_set_status_CMockStopIgnore(void);
#define lora_at_display_set_status_ExpectAnyArgsAndReturn(cmock_retval) lora_at_display_set_status_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void lora_at_display_set_status_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lora_at_display_set_status_ExpectAndReturn(status, display, cmock_retval) lora_at_display_set_status_CMockExpectAndReturn(__LINE__, status, display, cmock_retval)
void lora_at_display_set_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* status, lora_at_display* display, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_lora_at_display_set_status_CALLBACK)(const char* status, lora_at_display* display, int cmock_num_calls);
void lora_at_display_set_status_AddCallback(CMOCK_lora_at_display_set_status_CALLBACK Callback);
void lora_at_display_set_status_Stub(CMOCK_lora_at_display_set_status_CALLBACK Callback);
#define lora_at_display_set_status_StubWithCallback lora_at_display_set_status_Stub
#define lora_at_display_set_status_ExpectWithArrayAndReturn(status, display, display_Depth, cmock_retval) lora_at_display_set_status_CMockExpectWithArrayAndReturn(__LINE__, status, display, display_Depth, cmock_retval)
void lora_at_display_set_status_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const char* status, lora_at_display* display, int display_Depth, esp_err_t cmock_to_return);
#define lora_at_display_set_status_ReturnThruPtr_display(display) lora_at_display_set_status_CMockReturnMemThruPtr_display(__LINE__, display, sizeof(lora_at_display))
#define lora_at_display_set_status_ReturnArrayThruPtr_display(display, cmock_len) lora_at_display_set_status_CMockReturnMemThruPtr_display(__LINE__, display, (int)(cmock_len * (int)sizeof(*display)))
#define lora_at_display_set_status_ReturnMemThruPtr_display(display, cmock_size) lora_at_display_set_status_CMockReturnMemThruPtr_display(__LINE__, display, cmock_size)
void lora_at_display_set_status_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size);
#define lora_at_display_set_status_IgnoreArg_status() lora_at_display_set_status_CMockIgnoreArg_status(__LINE__)
void lora_at_display_set_status_CMockIgnoreArg_status(UNITY_LINE_TYPE cmock_line);
#define lora_at_display_set_status_IgnoreArg_display() lora_at_display_set_status_CMockIgnoreArg_display(__LINE__)
void lora_at_display_set_status_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line);
#define lora_at_display_destroy_Ignore() lora_at_display_destroy_CMockIgnore()
void lora_at_display_destroy_CMockIgnore(void);
#define lora_at_display_destroy_StopIgnore() lora_at_display_destroy_CMockStopIgnore()
void lora_at_display_destroy_CMockStopIgnore(void);
#define lora_at_display_destroy_ExpectAnyArgs() lora_at_display_destroy_CMockExpectAnyArgs(__LINE__)
void lora_at_display_destroy_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define lora_at_display_destroy_Expect(display) lora_at_display_destroy_CMockExpect(__LINE__, display)
void lora_at_display_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, lora_at_display* display);
typedef void (* CMOCK_lora_at_display_destroy_CALLBACK)(lora_at_display* display, int cmock_num_calls);
void lora_at_display_destroy_AddCallback(CMOCK_lora_at_display_destroy_CALLBACK Callback);
void lora_at_display_destroy_Stub(CMOCK_lora_at_display_destroy_CALLBACK Callback);
#define lora_at_display_destroy_StubWithCallback lora_at_display_destroy_Stub
#define lora_at_display_destroy_ExpectWithArray(display, display_Depth) lora_at_display_destroy_CMockExpectWithArray(__LINE__, display, display_Depth)
void lora_at_display_destroy_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int display_Depth);
#define lora_at_display_destroy_ReturnThruPtr_display(display) lora_at_display_destroy_CMockReturnMemThruPtr_display(__LINE__, display, sizeof(lora_at_display))
#define lora_at_display_destroy_ReturnArrayThruPtr_display(display, cmock_len) lora_at_display_destroy_CMockReturnMemThruPtr_display(__LINE__, display, (int)(cmock_len * (int)sizeof(*display)))
#define lora_at_display_destroy_ReturnMemThruPtr_display(display, cmock_size) lora_at_display_destroy_CMockReturnMemThruPtr_display(__LINE__, display, cmock_size)
void lora_at_display_destroy_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size);
#define lora_at_display_destroy_IgnoreArg_display() lora_at_display_destroy_CMockIgnoreArg_display(__LINE__)
void lora_at_display_destroy_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
