/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockdisplay.h"
#include "mock_helper.h"

static const char* CMockString_display = "display";
static const char* CMockString_lora_at_display_create = "lora_at_display_create";
static const char* CMockString_lora_at_display_destroy = "lora_at_display_destroy";
static const char* CMockString_lora_at_display_set_status = "lora_at_display_set_status";
static const char* CMockString_lora_at_display_start = "lora_at_display_start";
static const char* CMockString_lora_at_display_stop = "lora_at_display_stop";
static const char* CMockString_status = "status";

typedef struct _CMOCK_lora_at_display_create_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  lora_at_display** Expected_display;
  int Expected_display_Depth;
  char ReturnThruPtr_display_Used;
  lora_at_display** ReturnThruPtr_display_Val;
  int ReturnThruPtr_display_Size;
  char IgnoreArg_display;

} CMOCK_lora_at_display_create_CALL_INSTANCE;

typedef struct _CMOCK_lora_at_display_start_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  lora_at_display* Expected_display;
  int Expected_display_Depth;
  char ReturnThruPtr_display_Used;
  lora_at_display* ReturnThruPtr_display_Val;
  int ReturnThruPtr_display_Size;
  char IgnoreArg_display;

} CMOCK_lora_at_display_start_CALL_INSTANCE;

typedef struct _CMOCK_lora_at_display_stop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  lora_at_display* Expected_display;
  int Expected_display_Depth;
  char ReturnThruPtr_display_Used;
  lora_at_display* ReturnThruPtr_display_Val;
  int ReturnThruPtr_display_Size;
  char IgnoreArg_display;

} CMOCK_lora_at_display_stop_CALL_INSTANCE;

typedef struct _CMOCK_lora_at_display_set_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  const char* Expected_status;
  lora_at_display* Expected_display;
  int Expected_display_Depth;
  char ReturnThruPtr_display_Used;
  lora_at_display* ReturnThruPtr_display_Val;
  int ReturnThruPtr_display_Size;
  char IgnoreArg_status;
  char IgnoreArg_display;

} CMOCK_lora_at_display_set_status_CALL_INSTANCE;

typedef struct _CMOCK_lora_at_display_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  lora_at_display* Expected_display;
  int Expected_display_Depth;
  char ReturnThruPtr_display_Used;
  lora_at_display* ReturnThruPtr_display_Val;
  int ReturnThruPtr_display_Size;
  char IgnoreArg_display;

} CMOCK_lora_at_display_destroy_CALL_INSTANCE;

static struct MockdisplayInstance
{
  char lora_at_display_create_IgnoreBool;
  esp_err_t lora_at_display_create_FinalReturn;
  char lora_at_display_create_CallbackBool;
  CMOCK_lora_at_display_create_CALLBACK lora_at_display_create_CallbackFunctionPointer;
  int lora_at_display_create_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_at_display_create_CallInstance;
  char lora_at_display_start_IgnoreBool;
  esp_err_t lora_at_display_start_FinalReturn;
  char lora_at_display_start_CallbackBool;
  CMOCK_lora_at_display_start_CALLBACK lora_at_display_start_CallbackFunctionPointer;
  int lora_at_display_start_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_at_display_start_CallInstance;
  char lora_at_display_stop_IgnoreBool;
  esp_err_t lora_at_display_stop_FinalReturn;
  char lora_at_display_stop_CallbackBool;
  CMOCK_lora_at_display_stop_CALLBACK lora_at_display_stop_CallbackFunctionPointer;
  int lora_at_display_stop_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_at_display_stop_CallInstance;
  char lora_at_display_set_status_IgnoreBool;
  esp_err_t lora_at_display_set_status_FinalReturn;
  char lora_at_display_set_status_CallbackBool;
  CMOCK_lora_at_display_set_status_CALLBACK lora_at_display_set_status_CallbackFunctionPointer;
  int lora_at_display_set_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_at_display_set_status_CallInstance;
  char lora_at_display_destroy_IgnoreBool;
  char lora_at_display_destroy_CallbackBool;
  CMOCK_lora_at_display_destroy_CALLBACK lora_at_display_destroy_CallbackFunctionPointer;
  int lora_at_display_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lora_at_display_destroy_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockdisplay_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.lora_at_display_create_CallInstance;
  if (Mock.lora_at_display_create_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_at_display_create);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_at_display_create_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_at_display_start_CallInstance;
  if (Mock.lora_at_display_start_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_at_display_start);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_at_display_start_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_at_display_stop_CallInstance;
  if (Mock.lora_at_display_stop_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_at_display_stop);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_at_display_stop_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_at_display_set_status_CallInstance;
  if (Mock.lora_at_display_set_status_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_at_display_set_status);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_at_display_set_status_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.lora_at_display_destroy_CallInstance;
  if (Mock.lora_at_display_destroy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_lora_at_display_destroy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.lora_at_display_destroy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockdisplay_Init(void)
{
  Mockdisplay_Destroy();
}

void Mockdisplay_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t lora_at_display_create(lora_at_display** display)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_at_display_create);
  cmock_call_instance = (CMOCK_lora_at_display_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_at_display_create_CallInstance);
  Mock.lora_at_display_create_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_create_CallInstance);
  if (Mock.lora_at_display_create_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_at_display_create_FinalReturn;
    memcpy((void*)(&Mock.lora_at_display_create_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_at_display_create_CallbackBool &&
      Mock.lora_at_display_create_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_at_display_create_CallbackFunctionPointer(display, Mock.lora_at_display_create_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_display)
  {
    UNITY_SET_DETAILS(CMockString_lora_at_display_create,CMockString_display);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_display, display, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.lora_at_display_create_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_at_display_create_CallbackFunctionPointer(display, Mock.lora_at_display_create_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_display_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(display, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)display, (void*)cmock_call_instance->ReturnThruPtr_display_Val,
      cmock_call_instance->ReturnThruPtr_display_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_at_display_create(CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance, lora_at_display** display, int display_Depth)
{
  cmock_call_instance->Expected_display = display;
  cmock_call_instance->Expected_display_Depth = display_Depth;
  cmock_call_instance->IgnoreArg_display = 0;
  cmock_call_instance->ReturnThruPtr_display_Used = 0;
}

void lora_at_display_create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_create_CALL_INSTANCE));
  CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_create_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_create_CallInstance, cmock_guts_index);
  Mock.lora_at_display_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_at_display_create_IgnoreBool = (char)1;
}

void lora_at_display_create_CMockStopIgnore(void)
{
  if(Mock.lora_at_display_create_IgnoreBool)
    Mock.lora_at_display_create_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_create_CallInstance);
  Mock.lora_at_display_create_IgnoreBool = (char)0;
}

void lora_at_display_create_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_create_CALL_INSTANCE));
  CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_create_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_create_CallInstance, cmock_guts_index);
  Mock.lora_at_display_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_at_display_create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display** display, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_create_CALL_INSTANCE));
  CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_create_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_create_CallInstance, cmock_guts_index);
  Mock.lora_at_display_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_create(cmock_call_instance, display, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_at_display_create_AddCallback(CMOCK_lora_at_display_create_CALLBACK Callback)
{
  Mock.lora_at_display_create_IgnoreBool = (char)0;
  Mock.lora_at_display_create_CallbackBool = (char)1;
  Mock.lora_at_display_create_CallbackFunctionPointer = Callback;
}

void lora_at_display_create_Stub(CMOCK_lora_at_display_create_CALLBACK Callback)
{
  Mock.lora_at_display_create_IgnoreBool = (char)0;
  Mock.lora_at_display_create_CallbackBool = (char)0;
  Mock.lora_at_display_create_CallbackFunctionPointer = Callback;
}

void lora_at_display_create_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display** display, int display_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_create_CALL_INSTANCE));
  CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_create_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_create_CallInstance, cmock_guts_index);
  Mock.lora_at_display_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_create(cmock_call_instance, display, display_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_at_display_create_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display** display, int cmock_size)
{
  CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_display_Used = 1;
  cmock_call_instance->ReturnThruPtr_display_Val = display;
  cmock_call_instance->ReturnThruPtr_display_Size = cmock_size;
}

void lora_at_display_create_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_at_display_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_display = 1;
}

esp_err_t lora_at_display_start(lora_at_display* display)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_at_display_start);
  cmock_call_instance = (CMOCK_lora_at_display_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_at_display_start_CallInstance);
  Mock.lora_at_display_start_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_start_CallInstance);
  if (Mock.lora_at_display_start_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_at_display_start_FinalReturn;
    memcpy((void*)(&Mock.lora_at_display_start_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_at_display_start_CallbackBool &&
      Mock.lora_at_display_start_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_at_display_start_CallbackFunctionPointer(display, Mock.lora_at_display_start_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_display)
  {
    UNITY_SET_DETAILS(CMockString_lora_at_display_start,CMockString_display);
    if (cmock_call_instance->Expected_display == NULL)
      { UNITY_TEST_ASSERT_NULL(display, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_display), (void*)(display), sizeof(lora_at_display), cmock_call_instance->Expected_display_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.lora_at_display_start_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_at_display_start_CallbackFunctionPointer(display, Mock.lora_at_display_start_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_display_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(display, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)display, (void*)cmock_call_instance->ReturnThruPtr_display_Val,
      cmock_call_instance->ReturnThruPtr_display_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_at_display_start(CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance, lora_at_display* display, int display_Depth)
{
  cmock_call_instance->Expected_display = display;
  cmock_call_instance->Expected_display_Depth = display_Depth;
  cmock_call_instance->IgnoreArg_display = 0;
  cmock_call_instance->ReturnThruPtr_display_Used = 0;
}

void lora_at_display_start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_start_CALL_INSTANCE));
  CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_start_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_start_CallInstance, cmock_guts_index);
  Mock.lora_at_display_start_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_at_display_start_IgnoreBool = (char)1;
}

void lora_at_display_start_CMockStopIgnore(void)
{
  if(Mock.lora_at_display_start_IgnoreBool)
    Mock.lora_at_display_start_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_start_CallInstance);
  Mock.lora_at_display_start_IgnoreBool = (char)0;
}

void lora_at_display_start_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_start_CALL_INSTANCE));
  CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_start_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_start_CallInstance, cmock_guts_index);
  Mock.lora_at_display_start_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_at_display_start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_start_CALL_INSTANCE));
  CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_start_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_start_CallInstance, cmock_guts_index);
  Mock.lora_at_display_start_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_start(cmock_call_instance, display, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_at_display_start_AddCallback(CMOCK_lora_at_display_start_CALLBACK Callback)
{
  Mock.lora_at_display_start_IgnoreBool = (char)0;
  Mock.lora_at_display_start_CallbackBool = (char)1;
  Mock.lora_at_display_start_CallbackFunctionPointer = Callback;
}

void lora_at_display_start_Stub(CMOCK_lora_at_display_start_CALLBACK Callback)
{
  Mock.lora_at_display_start_IgnoreBool = (char)0;
  Mock.lora_at_display_start_CallbackBool = (char)0;
  Mock.lora_at_display_start_CallbackFunctionPointer = Callback;
}

void lora_at_display_start_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int display_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_start_CALL_INSTANCE));
  CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_start_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_start_CallInstance, cmock_guts_index);
  Mock.lora_at_display_start_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_start(cmock_call_instance, display, display_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_at_display_start_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size)
{
  CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_start_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_display_Used = 1;
  cmock_call_instance->ReturnThruPtr_display_Val = display;
  cmock_call_instance->ReturnThruPtr_display_Size = cmock_size;
}

void lora_at_display_start_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_at_display_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_start_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_display = 1;
}

esp_err_t lora_at_display_stop(lora_at_display* display)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_at_display_stop);
  cmock_call_instance = (CMOCK_lora_at_display_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_at_display_stop_CallInstance);
  Mock.lora_at_display_stop_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_stop_CallInstance);
  if (Mock.lora_at_display_stop_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_at_display_stop_FinalReturn;
    memcpy((void*)(&Mock.lora_at_display_stop_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_at_display_stop_CallbackBool &&
      Mock.lora_at_display_stop_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_at_display_stop_CallbackFunctionPointer(display, Mock.lora_at_display_stop_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_display)
  {
    UNITY_SET_DETAILS(CMockString_lora_at_display_stop,CMockString_display);
    if (cmock_call_instance->Expected_display == NULL)
      { UNITY_TEST_ASSERT_NULL(display, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_display), (void*)(display), sizeof(lora_at_display), cmock_call_instance->Expected_display_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.lora_at_display_stop_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_at_display_stop_CallbackFunctionPointer(display, Mock.lora_at_display_stop_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_display_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(display, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)display, (void*)cmock_call_instance->ReturnThruPtr_display_Val,
      cmock_call_instance->ReturnThruPtr_display_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_at_display_stop(CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance, lora_at_display* display, int display_Depth)
{
  cmock_call_instance->Expected_display = display;
  cmock_call_instance->Expected_display_Depth = display_Depth;
  cmock_call_instance->IgnoreArg_display = 0;
  cmock_call_instance->ReturnThruPtr_display_Used = 0;
}

void lora_at_display_stop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_stop_CALL_INSTANCE));
  CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_stop_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_stop_CallInstance, cmock_guts_index);
  Mock.lora_at_display_stop_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_at_display_stop_IgnoreBool = (char)1;
}

void lora_at_display_stop_CMockStopIgnore(void)
{
  if(Mock.lora_at_display_stop_IgnoreBool)
    Mock.lora_at_display_stop_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_stop_CallInstance);
  Mock.lora_at_display_stop_IgnoreBool = (char)0;
}

void lora_at_display_stop_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_stop_CALL_INSTANCE));
  CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_stop_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_stop_CallInstance, cmock_guts_index);
  Mock.lora_at_display_stop_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_at_display_stop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_stop_CALL_INSTANCE));
  CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_stop_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_stop_CallInstance, cmock_guts_index);
  Mock.lora_at_display_stop_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_stop(cmock_call_instance, display, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_at_display_stop_AddCallback(CMOCK_lora_at_display_stop_CALLBACK Callback)
{
  Mock.lora_at_display_stop_IgnoreBool = (char)0;
  Mock.lora_at_display_stop_CallbackBool = (char)1;
  Mock.lora_at_display_stop_CallbackFunctionPointer = Callback;
}

void lora_at_display_stop_Stub(CMOCK_lora_at_display_stop_CALLBACK Callback)
{
  Mock.lora_at_display_stop_IgnoreBool = (char)0;
  Mock.lora_at_display_stop_CallbackBool = (char)0;
  Mock.lora_at_display_stop_CallbackFunctionPointer = Callback;
}

void lora_at_display_stop_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int display_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_stop_CALL_INSTANCE));
  CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_stop_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_stop_CallInstance, cmock_guts_index);
  Mock.lora_at_display_stop_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_stop(cmock_call_instance, display, display_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_at_display_stop_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size)
{
  CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_stop_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_display_Used = 1;
  cmock_call_instance->ReturnThruPtr_display_Val = display;
  cmock_call_instance->ReturnThruPtr_display_Size = cmock_size;
}

void lora_at_display_stop_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_at_display_stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_stop_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_display = 1;
}

esp_err_t lora_at_display_set_status(const char* status, lora_at_display* display)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_at_display_set_status);
  cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_at_display_set_status_CallInstance);
  Mock.lora_at_display_set_status_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_set_status_CallInstance);
  if (Mock.lora_at_display_set_status_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.lora_at_display_set_status_FinalReturn;
    memcpy((void*)(&Mock.lora_at_display_set_status_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.lora_at_display_set_status_CallbackBool &&
      Mock.lora_at_display_set_status_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.lora_at_display_set_status_CallbackFunctionPointer(status, display, Mock.lora_at_display_set_status_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_status)
  {
    UNITY_SET_DETAILS(CMockString_lora_at_display_set_status,CMockString_status);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_status, status, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_display)
  {
    UNITY_SET_DETAILS(CMockString_lora_at_display_set_status,CMockString_display);
    if (cmock_call_instance->Expected_display == NULL)
      { UNITY_TEST_ASSERT_NULL(display, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_display), (void*)(display), sizeof(lora_at_display), cmock_call_instance->Expected_display_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.lora_at_display_set_status_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.lora_at_display_set_status_CallbackFunctionPointer(status, display, Mock.lora_at_display_set_status_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_display_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(display, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)display, (void*)cmock_call_instance->ReturnThruPtr_display_Val,
      cmock_call_instance->ReturnThruPtr_display_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_lora_at_display_set_status(CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance, const char* status, lora_at_display* display, int display_Depth)
{
  cmock_call_instance->Expected_status = status;
  cmock_call_instance->IgnoreArg_status = 0;
  cmock_call_instance->Expected_display = display;
  cmock_call_instance->Expected_display_Depth = display_Depth;
  cmock_call_instance->IgnoreArg_display = 0;
  cmock_call_instance->ReturnThruPtr_display_Used = 0;
}

void lora_at_display_set_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_set_status_CALL_INSTANCE));
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_set_status_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_set_status_CallInstance, cmock_guts_index);
  Mock.lora_at_display_set_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lora_at_display_set_status_IgnoreBool = (char)1;
}

void lora_at_display_set_status_CMockStopIgnore(void)
{
  if(Mock.lora_at_display_set_status_IgnoreBool)
    Mock.lora_at_display_set_status_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_set_status_CallInstance);
  Mock.lora_at_display_set_status_IgnoreBool = (char)0;
}

void lora_at_display_set_status_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_set_status_CALL_INSTANCE));
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_set_status_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_set_status_CallInstance, cmock_guts_index);
  Mock.lora_at_display_set_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_at_display_set_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* status, lora_at_display* display, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_set_status_CALL_INSTANCE));
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_set_status_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_set_status_CallInstance, cmock_guts_index);
  Mock.lora_at_display_set_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_set_status(cmock_call_instance, status, display, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void lora_at_display_set_status_AddCallback(CMOCK_lora_at_display_set_status_CALLBACK Callback)
{
  Mock.lora_at_display_set_status_IgnoreBool = (char)0;
  Mock.lora_at_display_set_status_CallbackBool = (char)1;
  Mock.lora_at_display_set_status_CallbackFunctionPointer = Callback;
}

void lora_at_display_set_status_Stub(CMOCK_lora_at_display_set_status_CALLBACK Callback)
{
  Mock.lora_at_display_set_status_IgnoreBool = (char)0;
  Mock.lora_at_display_set_status_CallbackBool = (char)0;
  Mock.lora_at_display_set_status_CallbackFunctionPointer = Callback;
}

void lora_at_display_set_status_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const char* status, lora_at_display* display, int display_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_set_status_CALL_INSTANCE));
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_set_status_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_set_status_CallInstance, cmock_guts_index);
  Mock.lora_at_display_set_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_set_status(cmock_call_instance, status, display, display_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lora_at_display_set_status_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size)
{
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_set_status_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_display_Used = 1;
  cmock_call_instance->ReturnThruPtr_display_Val = display;
  cmock_call_instance->ReturnThruPtr_display_Size = cmock_size;
}

void lora_at_display_set_status_CMockIgnoreArg_status(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_set_status_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_status = 1;
}

void lora_at_display_set_status_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_at_display_set_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_set_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_set_status_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_display = 1;
}

void lora_at_display_destroy(lora_at_display* display)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lora_at_display_destroy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lora_at_display_destroy);
  cmock_call_instance = (CMOCK_lora_at_display_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lora_at_display_destroy_CallInstance);
  Mock.lora_at_display_destroy_CallInstance = CMock_Guts_MemNext(Mock.lora_at_display_destroy_CallInstance);
  if (Mock.lora_at_display_destroy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.lora_at_display_destroy_CallbackBool &&
      Mock.lora_at_display_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.lora_at_display_destroy_CallbackFunctionPointer(display, Mock.lora_at_display_destroy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_display)
  {
    UNITY_SET_DETAILS(CMockString_lora_at_display_destroy,CMockString_display);
    if (cmock_call_instance->Expected_display == NULL)
      { UNITY_TEST_ASSERT_NULL(display, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_display), (void*)(display), sizeof(lora_at_display), cmock_call_instance->Expected_display_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.lora_at_display_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.lora_at_display_destroy_CallbackFunctionPointer(display, Mock.lora_at_display_destroy_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_display_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(display, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)display, (void*)cmock_call_instance->ReturnThruPtr_display_Val,
      cmock_call_instance->ReturnThruPtr_display_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_lora_at_display_destroy(CMOCK_lora_at_display_destroy_CALL_INSTANCE* cmock_call_instance, lora_at_display* display, int display_Depth)
{
  cmock_call_instance->Expected_display = display;
  cmock_call_instance->Expected_display_Depth = display_Depth;
  cmock_call_instance->IgnoreArg_display = 0;
  cmock_call_instance->ReturnThruPtr_display_Used = 0;
}

void lora_at_display_destroy_CMockIgnore(void)
{
  Mock.lora_at_display_destroy_IgnoreBool = (char)1;
}

void lora_at_display_destroy_CMockStopIgnore(void)
{
  Mock.lora_at_display_destroy_IgnoreBool = (char)0;
}

void lora_at_display_destroy_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_destroy_CALL_INSTANCE));
  CMOCK_lora_at_display_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_destroy_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_destroy_CallInstance, cmock_guts_index);
  Mock.lora_at_display_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void lora_at_display_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, lora_at_display* display)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_destroy_CALL_INSTANCE));
  CMOCK_lora_at_display_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_destroy_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_destroy_CallInstance, cmock_guts_index);
  Mock.lora_at_display_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_destroy(cmock_call_instance, display, 1);
}

void lora_at_display_destroy_AddCallback(CMOCK_lora_at_display_destroy_CALLBACK Callback)
{
  Mock.lora_at_display_destroy_IgnoreBool = (char)0;
  Mock.lora_at_display_destroy_CallbackBool = (char)1;
  Mock.lora_at_display_destroy_CallbackFunctionPointer = Callback;
}

void lora_at_display_destroy_Stub(CMOCK_lora_at_display_destroy_CALLBACK Callback)
{
  Mock.lora_at_display_destroy_IgnoreBool = (char)0;
  Mock.lora_at_display_destroy_CallbackBool = (char)0;
  Mock.lora_at_display_destroy_CallbackFunctionPointer = Callback;
}

void lora_at_display_destroy_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int display_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lora_at_display_destroy_CALL_INSTANCE));
  CMOCK_lora_at_display_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lora_at_display_destroy_CallInstance = CMock_Guts_MemChain(Mock.lora_at_display_destroy_CallInstance, cmock_guts_index);
  Mock.lora_at_display_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_lora_at_display_destroy(cmock_call_instance, display, display_Depth);
}

void lora_at_display_destroy_CMockReturnMemThruPtr_display(UNITY_LINE_TYPE cmock_line, lora_at_display* display, int cmock_size)
{
  CMOCK_lora_at_display_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_destroy_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_display_Used = 1;
  cmock_call_instance->ReturnThruPtr_display_Val = display;
  cmock_call_instance->ReturnThruPtr_display_Size = cmock_size;
}

void lora_at_display_destroy_CMockIgnoreArg_display(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_lora_at_display_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_lora_at_display_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.lora_at_display_destroy_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_display = 1;
}

