/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "driver/Mockuart.h"
#include "mock_helper.h"

static const char* CMockString_buf = "buf";
static const char* CMockString_length = "length";
static const char* CMockString_size = "size";
static const char* CMockString_src = "src";
static const char* CMockString_ticks_to_wait = "ticks_to_wait";
static const char* CMockString_uart_num = "uart_num";
static const char* CMockString_uart_read_bytes = "uart_read_bytes";
static const char* CMockString_uart_write_bytes = "uart_write_bytes";

typedef struct _CMOCK_uart_write_bytes_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uart_port_t Expected_uart_num;
  const void* Expected_src;
  size_t Expected_size;
  int Expected_src_Depth;
  char IgnoreArg_uart_num;
  char IgnoreArg_src;
  char IgnoreArg_size;

} CMOCK_uart_write_bytes_CALL_INSTANCE;

typedef struct _CMOCK_uart_read_bytes_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uart_port_t Expected_uart_num;
  void* Expected_buf;
  uint32_t Expected_length;
  TickType_t Expected_ticks_to_wait;
  int Expected_buf_Depth;
  char ReturnThruPtr_buf_Used;
  void* ReturnThruPtr_buf_Val;
  int ReturnThruPtr_buf_Size;
  char IgnoreArg_uart_num;
  char IgnoreArg_buf;
  char IgnoreArg_length;
  char IgnoreArg_ticks_to_wait;

} CMOCK_uart_read_bytes_CALL_INSTANCE;

static struct MockuartInstance
{
  char uart_write_bytes_IgnoreBool;
  int uart_write_bytes_FinalReturn;
  char uart_write_bytes_CallbackBool;
  CMOCK_uart_write_bytes_CALLBACK uart_write_bytes_CallbackFunctionPointer;
  int uart_write_bytes_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE uart_write_bytes_CallInstance;
  char uart_read_bytes_IgnoreBool;
  int uart_read_bytes_FinalReturn;
  char uart_read_bytes_CallbackBool;
  CMOCK_uart_read_bytes_CALLBACK uart_read_bytes_CallbackFunctionPointer;
  int uart_read_bytes_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE uart_read_bytes_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockuart_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.uart_write_bytes_CallInstance;
  if (Mock.uart_write_bytes_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_write_bytes);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.uart_write_bytes_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.uart_read_bytes_CallInstance;
  if (Mock.uart_read_bytes_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_read_bytes);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.uart_read_bytes_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockuart_Init(void)
{
  Mockuart_Destroy();
}

void Mockuart_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int uart_write_bytes(uart_port_t uart_num, const void* src, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_write_bytes);
  cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_write_bytes_CallInstance);
  Mock.uart_write_bytes_CallInstance = CMock_Guts_MemNext(Mock.uart_write_bytes_CallInstance);
  if (Mock.uart_write_bytes_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.uart_write_bytes_FinalReturn;
    Mock.uart_write_bytes_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.uart_write_bytes_CallbackBool &&
      Mock.uart_write_bytes_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.uart_write_bytes_CallbackFunctionPointer(uart_num, src, size, Mock.uart_write_bytes_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_uart_num)
  {
    UNITY_SET_DETAILS(CMockString_uart_write_bytes,CMockString_uart_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_uart_num), (void*)(&uart_num), sizeof(uart_port_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_src)
  {
    UNITY_SET_DETAILS(CMockString_uart_write_bytes,CMockString_src);
    if (cmock_call_instance->Expected_src == NULL)
      { UNITY_TEST_ASSERT_NULL(src, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_src, src, cmock_call_instance->Expected_src_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_uart_write_bytes,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.uart_write_bytes_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.uart_write_bytes_CallbackFunctionPointer(uart_num, src, size, Mock.uart_write_bytes_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_write_bytes(CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance, uart_port_t uart_num, const void* src, int src_Depth, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_uart_num), (void*)(&uart_num),
         sizeof(uart_port_t[sizeof(uart_num) == sizeof(uart_port_t) ? 1 : -1])); /* add uart_port_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_uart_num = 0;
  cmock_call_instance->Expected_src = src;
  cmock_call_instance->Expected_src_Depth = src_Depth;
  cmock_call_instance->IgnoreArg_src = 0;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_size = 0;
}

void uart_write_bytes_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_write_bytes_CALL_INSTANCE));
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_write_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_write_bytes_CallInstance, cmock_guts_index);
  Mock.uart_write_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.uart_write_bytes_IgnoreBool = (char)1;
}

void uart_write_bytes_CMockStopIgnore(void)
{
  if(Mock.uart_write_bytes_IgnoreBool)
    Mock.uart_write_bytes_CallInstance = CMock_Guts_MemNext(Mock.uart_write_bytes_CallInstance);
  Mock.uart_write_bytes_IgnoreBool = (char)0;
}

void uart_write_bytes_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_write_bytes_CALL_INSTANCE));
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_write_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_write_bytes_CallInstance, cmock_guts_index);
  Mock.uart_write_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void uart_write_bytes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uart_port_t uart_num, const void* src, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_write_bytes_CALL_INSTANCE));
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_write_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_write_bytes_CallInstance, cmock_guts_index);
  Mock.uart_write_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_uart_write_bytes(cmock_call_instance, uart_num, src, size, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void uart_write_bytes_AddCallback(CMOCK_uart_write_bytes_CALLBACK Callback)
{
  Mock.uart_write_bytes_IgnoreBool = (char)0;
  Mock.uart_write_bytes_CallbackBool = (char)1;
  Mock.uart_write_bytes_CallbackFunctionPointer = Callback;
}

void uart_write_bytes_Stub(CMOCK_uart_write_bytes_CALLBACK Callback)
{
  Mock.uart_write_bytes_IgnoreBool = (char)0;
  Mock.uart_write_bytes_CallbackBool = (char)0;
  Mock.uart_write_bytes_CallbackFunctionPointer = Callback;
}

void uart_write_bytes_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uart_port_t uart_num, const void* src, int src_Depth, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_write_bytes_CALL_INSTANCE));
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_write_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_write_bytes_CallInstance, cmock_guts_index);
  Mock.uart_write_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_uart_write_bytes(cmock_call_instance, uart_num, src, src_Depth, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void uart_write_bytes_CMockIgnoreArg_uart_num(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_write_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_uart_num = 1;
}

void uart_write_bytes_CMockIgnoreArg_src(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_write_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_src = 1;
}

void uart_write_bytes_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart_write_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_write_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_write_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

int uart_read_bytes(uart_port_t uart_num, void* buf, uint32_t length, TickType_t ticks_to_wait)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_read_bytes);
  cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_read_bytes_CallInstance);
  Mock.uart_read_bytes_CallInstance = CMock_Guts_MemNext(Mock.uart_read_bytes_CallInstance);
  if (Mock.uart_read_bytes_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.uart_read_bytes_FinalReturn;
    Mock.uart_read_bytes_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.uart_read_bytes_CallbackBool &&
      Mock.uart_read_bytes_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.uart_read_bytes_CallbackFunctionPointer(uart_num, buf, length, ticks_to_wait, Mock.uart_read_bytes_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_uart_num)
  {
    UNITY_SET_DETAILS(CMockString_uart_read_bytes,CMockString_uart_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_uart_num), (void*)(&uart_num), sizeof(uart_port_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_buf)
  {
    UNITY_SET_DETAILS(CMockString_uart_read_bytes,CMockString_buf);
    if (cmock_call_instance->Expected_buf == NULL)
      { UNITY_TEST_ASSERT_NULL(buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buf, buf, cmock_call_instance->Expected_buf_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_uart_read_bytes,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_ticks_to_wait)
  {
    UNITY_SET_DETAILS(CMockString_uart_read_bytes,CMockString_ticks_to_wait);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ticks_to_wait), (void*)(&ticks_to_wait), sizeof(TickType_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.uart_read_bytes_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.uart_read_bytes_CallbackFunctionPointer(uart_num, buf, length, ticks_to_wait, Mock.uart_read_bytes_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buf_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buf, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buf, (void*)cmock_call_instance->ReturnThruPtr_buf_Val,
      cmock_call_instance->ReturnThruPtr_buf_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_read_bytes(CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance, uart_port_t uart_num, void* buf, int buf_Depth, uint32_t length, TickType_t ticks_to_wait)
{
  memcpy((void*)(&cmock_call_instance->Expected_uart_num), (void*)(&uart_num),
         sizeof(uart_port_t[sizeof(uart_num) == sizeof(uart_port_t) ? 1 : -1])); /* add uart_port_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_uart_num = 0;
  cmock_call_instance->Expected_buf = buf;
  cmock_call_instance->Expected_buf_Depth = buf_Depth;
  cmock_call_instance->IgnoreArg_buf = 0;
  cmock_call_instance->ReturnThruPtr_buf_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
  memcpy((void*)(&cmock_call_instance->Expected_ticks_to_wait), (void*)(&ticks_to_wait),
         sizeof(TickType_t[sizeof(ticks_to_wait) == sizeof(TickType_t) ? 1 : -1])); /* add TickType_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_ticks_to_wait = 0;
}

void uart_read_bytes_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_read_bytes_CALL_INSTANCE));
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_read_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_read_bytes_CallInstance, cmock_guts_index);
  Mock.uart_read_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.uart_read_bytes_IgnoreBool = (char)1;
}

void uart_read_bytes_CMockStopIgnore(void)
{
  if(Mock.uart_read_bytes_IgnoreBool)
    Mock.uart_read_bytes_CallInstance = CMock_Guts_MemNext(Mock.uart_read_bytes_CallInstance);
  Mock.uart_read_bytes_IgnoreBool = (char)0;
}

void uart_read_bytes_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_read_bytes_CALL_INSTANCE));
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_read_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_read_bytes_CallInstance, cmock_guts_index);
  Mock.uart_read_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void uart_read_bytes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uart_port_t uart_num, void* buf, uint32_t length, TickType_t ticks_to_wait, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_read_bytes_CALL_INSTANCE));
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_read_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_read_bytes_CallInstance, cmock_guts_index);
  Mock.uart_read_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_uart_read_bytes(cmock_call_instance, uart_num, buf, 1, length, ticks_to_wait);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void uart_read_bytes_AddCallback(CMOCK_uart_read_bytes_CALLBACK Callback)
{
  Mock.uart_read_bytes_IgnoreBool = (char)0;
  Mock.uart_read_bytes_CallbackBool = (char)1;
  Mock.uart_read_bytes_CallbackFunctionPointer = Callback;
}

void uart_read_bytes_Stub(CMOCK_uart_read_bytes_CALLBACK Callback)
{
  Mock.uart_read_bytes_IgnoreBool = (char)0;
  Mock.uart_read_bytes_CallbackBool = (char)0;
  Mock.uart_read_bytes_CallbackFunctionPointer = Callback;
}

void uart_read_bytes_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uart_port_t uart_num, void* buf, int buf_Depth, uint32_t length, TickType_t ticks_to_wait, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_read_bytes_CALL_INSTANCE));
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_read_bytes_CallInstance = CMock_Guts_MemChain(Mock.uart_read_bytes_CallInstance, cmock_guts_index);
  Mock.uart_read_bytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_uart_read_bytes(cmock_call_instance, uart_num, buf, buf_Depth, length, ticks_to_wait);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void uart_read_bytes_CMockReturnMemThruPtr_buf(UNITY_LINE_TYPE cmock_line, void* buf, int cmock_size)
{
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_read_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buf_Used = 1;
  cmock_call_instance->ReturnThruPtr_buf_Val = buf;
  cmock_call_instance->ReturnThruPtr_buf_Size = cmock_size;
}

void uart_read_bytes_CMockIgnoreArg_uart_num(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_read_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_uart_num = 1;
}

void uart_read_bytes_CMockIgnoreArg_buf(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_read_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buf = 1;
}

void uart_read_bytes_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_read_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

void uart_read_bytes_CMockIgnoreArg_ticks_to_wait(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart_read_bytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_read_bytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart_read_bytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ticks_to_wait = 1;
}

