/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockble_client.h"
#include "ble_client_mock_helper.h"

static const char* CMockString_address = "address";
static const char* CMockString_app_id = "app_id";
static const char* CMockString_ble_client_connect = "ble_client_connect";
static const char* CMockString_ble_client_create = "ble_client_create";
static const char* CMockString_ble_client_destroy = "ble_client_destroy";
static const char* CMockString_client = "client";

typedef struct _CMOCK_ble_client_create_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  uint16_t Expected_app_id;
  ble_client** Expected_client;
  int Expected_client_Depth;
  char ReturnThruPtr_client_Used;
  ble_client** ReturnThruPtr_client_Val;
  int ReturnThruPtr_client_Size;
  char IgnoreArg_app_id;
  char IgnoreArg_client;

} CMOCK_ble_client_create_CALL_INSTANCE;

typedef struct _CMOCK_ble_client_connect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  uint8_t* Expected_address;
  ble_client* Expected_client;
  int Expected_address_Depth;
  int Expected_client_Depth;
  char ReturnThruPtr_address_Used;
  uint8_t* ReturnThruPtr_address_Val;
  int ReturnThruPtr_address_Size;
  char ReturnThruPtr_client_Used;
  ble_client* ReturnThruPtr_client_Val;
  int ReturnThruPtr_client_Size;
  char IgnoreArg_address;
  char IgnoreArg_client;

} CMOCK_ble_client_connect_CALL_INSTANCE;

typedef struct _CMOCK_ble_client_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  ble_client* Expected_client;
  int Expected_client_Depth;
  char ReturnThruPtr_client_Used;
  ble_client* ReturnThruPtr_client_Val;
  int ReturnThruPtr_client_Size;
  char IgnoreArg_client;

} CMOCK_ble_client_destroy_CALL_INSTANCE;

static struct Mockble_clientInstance
{
  char ble_client_create_IgnoreBool;
  esp_err_t ble_client_create_FinalReturn;
  char ble_client_create_CallbackBool;
  CMOCK_ble_client_create_CALLBACK ble_client_create_CallbackFunctionPointer;
  int ble_client_create_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ble_client_create_CallInstance;
  char ble_client_connect_IgnoreBool;
  esp_err_t ble_client_connect_FinalReturn;
  char ble_client_connect_CallbackBool;
  CMOCK_ble_client_connect_CALLBACK ble_client_connect_CallbackFunctionPointer;
  int ble_client_connect_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ble_client_connect_CallInstance;
  char ble_client_destroy_IgnoreBool;
  char ble_client_destroy_CallbackBool;
  CMOCK_ble_client_destroy_CALLBACK ble_client_destroy_CallbackFunctionPointer;
  int ble_client_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ble_client_destroy_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockble_client_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.ble_client_create_CallInstance;
  if (Mock.ble_client_create_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ble_client_create);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ble_client_create_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ble_client_connect_CallInstance;
  if (Mock.ble_client_connect_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ble_client_connect);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ble_client_connect_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ble_client_destroy_CallInstance;
  if (Mock.ble_client_destroy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ble_client_destroy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ble_client_destroy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockble_client_Init(void)
{
  Mockble_client_Destroy();
}

void Mockble_client_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t ble_client_create(uint16_t app_id, ble_client** client)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ble_client_create);
  cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ble_client_create_CallInstance);
  Mock.ble_client_create_CallInstance = CMock_Guts_MemNext(Mock.ble_client_create_CallInstance);
  if (Mock.ble_client_create_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ble_client_create_FinalReturn;
    memcpy((void*)(&Mock.ble_client_create_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ble_client_create_CallbackBool &&
      Mock.ble_client_create_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.ble_client_create_CallbackFunctionPointer(app_id, client, Mock.ble_client_create_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_app_id)
  {
    UNITY_SET_DETAILS(CMockString_ble_client_create,CMockString_app_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_app_id, app_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_client)
  {
    UNITY_SET_DETAILS(CMockString_ble_client_create,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_client, client, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.ble_client_create_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ble_client_create_CallbackFunctionPointer(app_id, client, Mock.ble_client_create_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_client_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(client, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)client, (void*)cmock_call_instance->ReturnThruPtr_client_Val,
      cmock_call_instance->ReturnThruPtr_client_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ble_client_create(CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance, uint16_t app_id, ble_client** client, int client_Depth)
{
  cmock_call_instance->Expected_app_id = app_id;
  cmock_call_instance->IgnoreArg_app_id = 0;
  cmock_call_instance->Expected_client = client;
  cmock_call_instance->Expected_client_Depth = client_Depth;
  cmock_call_instance->IgnoreArg_client = 0;
  cmock_call_instance->ReturnThruPtr_client_Used = 0;
}

void ble_client_create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_create_CALL_INSTANCE));
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_create_CallInstance = CMock_Guts_MemChain(Mock.ble_client_create_CallInstance, cmock_guts_index);
  Mock.ble_client_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ble_client_create_IgnoreBool = (char)1;
}

void ble_client_create_CMockStopIgnore(void)
{
  if(Mock.ble_client_create_IgnoreBool)
    Mock.ble_client_create_CallInstance = CMock_Guts_MemNext(Mock.ble_client_create_CallInstance);
  Mock.ble_client_create_IgnoreBool = (char)0;
}

void ble_client_create_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_create_CALL_INSTANCE));
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_create_CallInstance = CMock_Guts_MemChain(Mock.ble_client_create_CallInstance, cmock_guts_index);
  Mock.ble_client_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ble_client_create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t app_id, ble_client** client, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_create_CALL_INSTANCE));
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_create_CallInstance = CMock_Guts_MemChain(Mock.ble_client_create_CallInstance, cmock_guts_index);
  Mock.ble_client_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ble_client_create(cmock_call_instance, app_id, client, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void ble_client_create_AddCallback(CMOCK_ble_client_create_CALLBACK Callback)
{
  Mock.ble_client_create_IgnoreBool = (char)0;
  Mock.ble_client_create_CallbackBool = (char)1;
  Mock.ble_client_create_CallbackFunctionPointer = Callback;
}

void ble_client_create_Stub(CMOCK_ble_client_create_CALLBACK Callback)
{
  Mock.ble_client_create_IgnoreBool = (char)0;
  Mock.ble_client_create_CallbackBool = (char)0;
  Mock.ble_client_create_CallbackFunctionPointer = Callback;
}

void ble_client_create_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t app_id, ble_client** client, int client_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_create_CALL_INSTANCE));
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_create_CallInstance = CMock_Guts_MemChain(Mock.ble_client_create_CallInstance, cmock_guts_index);
  Mock.ble_client_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ble_client_create(cmock_call_instance, app_id, client, client_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ble_client_create_CMockReturnMemThruPtr_client(UNITY_LINE_TYPE cmock_line, ble_client** client, int cmock_size)
{
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_client_Used = 1;
  cmock_call_instance->ReturnThruPtr_client_Val = client;
  cmock_call_instance->ReturnThruPtr_client_Size = cmock_size;
}

void ble_client_create_CMockIgnoreArg_app_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_app_id = 1;
}

void ble_client_create_CMockIgnoreArg_client(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ble_client_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_client = 1;
}

esp_err_t ble_client_connect(uint8_t* address, ble_client* client)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ble_client_connect);
  cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ble_client_connect_CallInstance);
  Mock.ble_client_connect_CallInstance = CMock_Guts_MemNext(Mock.ble_client_connect_CallInstance);
  if (Mock.ble_client_connect_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ble_client_connect_FinalReturn;
    memcpy((void*)(&Mock.ble_client_connect_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ble_client_connect_CallbackBool &&
      Mock.ble_client_connect_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.ble_client_connect_CallbackFunctionPointer(address, client, Mock.ble_client_connect_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_ble_client_connect,CMockString_address);
    if (cmock_call_instance->Expected_address == NULL)
      { UNITY_TEST_ASSERT_NULL(address, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_address, address, cmock_call_instance->Expected_address_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_client)
  {
    UNITY_SET_DETAILS(CMockString_ble_client_connect,CMockString_client);
    if (cmock_call_instance->Expected_client == NULL)
      { UNITY_TEST_ASSERT_NULL(client, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_client), (void*)(client), sizeof(ble_client), cmock_call_instance->Expected_client_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.ble_client_connect_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ble_client_connect_CallbackFunctionPointer(address, client, Mock.ble_client_connect_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_address_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(address, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)address, (void*)cmock_call_instance->ReturnThruPtr_address_Val,
      cmock_call_instance->ReturnThruPtr_address_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_client_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(client, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)client, (void*)cmock_call_instance->ReturnThruPtr_client_Val,
      cmock_call_instance->ReturnThruPtr_client_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ble_client_connect(CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance, uint8_t* address, int address_Depth, ble_client* client, int client_Depth)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->Expected_address_Depth = address_Depth;
  cmock_call_instance->IgnoreArg_address = 0;
  cmock_call_instance->ReturnThruPtr_address_Used = 0;
  cmock_call_instance->Expected_client = client;
  cmock_call_instance->Expected_client_Depth = client_Depth;
  cmock_call_instance->IgnoreArg_client = 0;
  cmock_call_instance->ReturnThruPtr_client_Used = 0;
}

void ble_client_connect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_connect_CALL_INSTANCE));
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_connect_CallInstance = CMock_Guts_MemChain(Mock.ble_client_connect_CallInstance, cmock_guts_index);
  Mock.ble_client_connect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ble_client_connect_IgnoreBool = (char)1;
}

void ble_client_connect_CMockStopIgnore(void)
{
  if(Mock.ble_client_connect_IgnoreBool)
    Mock.ble_client_connect_CallInstance = CMock_Guts_MemNext(Mock.ble_client_connect_CallInstance);
  Mock.ble_client_connect_IgnoreBool = (char)0;
}

void ble_client_connect_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_connect_CALL_INSTANCE));
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_connect_CallInstance = CMock_Guts_MemChain(Mock.ble_client_connect_CallInstance, cmock_guts_index);
  Mock.ble_client_connect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ble_client_connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* address, ble_client* client, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_connect_CALL_INSTANCE));
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_connect_CallInstance = CMock_Guts_MemChain(Mock.ble_client_connect_CallInstance, cmock_guts_index);
  Mock.ble_client_connect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ble_client_connect(cmock_call_instance, address, 1, client, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void ble_client_connect_AddCallback(CMOCK_ble_client_connect_CALLBACK Callback)
{
  Mock.ble_client_connect_IgnoreBool = (char)0;
  Mock.ble_client_connect_CallbackBool = (char)1;
  Mock.ble_client_connect_CallbackFunctionPointer = Callback;
}

void ble_client_connect_Stub(CMOCK_ble_client_connect_CALLBACK Callback)
{
  Mock.ble_client_connect_IgnoreBool = (char)0;
  Mock.ble_client_connect_CallbackBool = (char)0;
  Mock.ble_client_connect_CallbackFunctionPointer = Callback;
}

void ble_client_connect_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* address, int address_Depth, ble_client* client, int client_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_connect_CALL_INSTANCE));
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_connect_CallInstance = CMock_Guts_MemChain(Mock.ble_client_connect_CallInstance, cmock_guts_index);
  Mock.ble_client_connect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ble_client_connect(cmock_call_instance, address, address_Depth, client, client_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ble_client_connect_CMockReturnMemThruPtr_address(UNITY_LINE_TYPE cmock_line, uint8_t* address, int cmock_size)
{
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_connect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_address_Used = 1;
  cmock_call_instance->ReturnThruPtr_address_Val = address;
  cmock_call_instance->ReturnThruPtr_address_Size = cmock_size;
}

void ble_client_connect_CMockReturnMemThruPtr_client(UNITY_LINE_TYPE cmock_line, ble_client* client, int cmock_size)
{
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_connect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_client_Used = 1;
  cmock_call_instance->ReturnThruPtr_client_Val = client;
  cmock_call_instance->ReturnThruPtr_client_Size = cmock_size;
}

void ble_client_connect_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_connect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void ble_client_connect_CMockIgnoreArg_client(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ble_client_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_connect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_client = 1;
}

void ble_client_destroy(ble_client* client)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ble_client_destroy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ble_client_destroy);
  cmock_call_instance = (CMOCK_ble_client_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ble_client_destroy_CallInstance);
  Mock.ble_client_destroy_CallInstance = CMock_Guts_MemNext(Mock.ble_client_destroy_CallInstance);
  if (Mock.ble_client_destroy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.ble_client_destroy_CallbackBool &&
      Mock.ble_client_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.ble_client_destroy_CallbackFunctionPointer(client, Mock.ble_client_destroy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_client)
  {
    UNITY_SET_DETAILS(CMockString_ble_client_destroy,CMockString_client);
    if (cmock_call_instance->Expected_client == NULL)
      { UNITY_TEST_ASSERT_NULL(client, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_client), (void*)(client), sizeof(ble_client), cmock_call_instance->Expected_client_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.ble_client_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.ble_client_destroy_CallbackFunctionPointer(client, Mock.ble_client_destroy_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_client_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(client, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)client, (void*)cmock_call_instance->ReturnThruPtr_client_Val,
      cmock_call_instance->ReturnThruPtr_client_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_ble_client_destroy(CMOCK_ble_client_destroy_CALL_INSTANCE* cmock_call_instance, ble_client* client, int client_Depth)
{
  cmock_call_instance->Expected_client = client;
  cmock_call_instance->Expected_client_Depth = client_Depth;
  cmock_call_instance->IgnoreArg_client = 0;
  cmock_call_instance->ReturnThruPtr_client_Used = 0;
}

void ble_client_destroy_CMockIgnore(void)
{
  Mock.ble_client_destroy_IgnoreBool = (char)1;
}

void ble_client_destroy_CMockStopIgnore(void)
{
  Mock.ble_client_destroy_IgnoreBool = (char)0;
}

void ble_client_destroy_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_destroy_CALL_INSTANCE));
  CMOCK_ble_client_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_destroy_CallInstance = CMock_Guts_MemChain(Mock.ble_client_destroy_CallInstance, cmock_guts_index);
  Mock.ble_client_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ble_client_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, ble_client* client)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_destroy_CALL_INSTANCE));
  CMOCK_ble_client_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_destroy_CallInstance = CMock_Guts_MemChain(Mock.ble_client_destroy_CallInstance, cmock_guts_index);
  Mock.ble_client_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ble_client_destroy(cmock_call_instance, client, 1);
}

void ble_client_destroy_AddCallback(CMOCK_ble_client_destroy_CALLBACK Callback)
{
  Mock.ble_client_destroy_IgnoreBool = (char)0;
  Mock.ble_client_destroy_CallbackBool = (char)1;
  Mock.ble_client_destroy_CallbackFunctionPointer = Callback;
}

void ble_client_destroy_Stub(CMOCK_ble_client_destroy_CALLBACK Callback)
{
  Mock.ble_client_destroy_IgnoreBool = (char)0;
  Mock.ble_client_destroy_CallbackBool = (char)0;
  Mock.ble_client_destroy_CallbackFunctionPointer = Callback;
}

void ble_client_destroy_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, ble_client* client, int client_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ble_client_destroy_CALL_INSTANCE));
  CMOCK_ble_client_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ble_client_destroy_CallInstance = CMock_Guts_MemChain(Mock.ble_client_destroy_CallInstance, cmock_guts_index);
  Mock.ble_client_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ble_client_destroy(cmock_call_instance, client, client_Depth);
}

void ble_client_destroy_CMockReturnMemThruPtr_client(UNITY_LINE_TYPE cmock_line, ble_client* client, int cmock_size)
{
  CMOCK_ble_client_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_destroy_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_client_Used = 1;
  cmock_call_instance->ReturnThruPtr_client_Val = client;
  cmock_call_instance->ReturnThruPtr_client_Size = cmock_size;
}

void ble_client_destroy_CMockIgnoreArg_client(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ble_client_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_ble_client_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ble_client_destroy_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_client = 1;
}

