        :cmock:
          :plugins:
            - expect
            - expect_any_args
            - return_thru_ptr
            - array
            - ignore
            - ignore_arg
            - callback
          :mock_path: .
          :unity_helper:
            - sx127x_util_mock_helper.h

